name: Release and Deploy
on:
  pull_request:
    types: [closed]
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  create-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.VERSION }}
      tag: ${{ steps.get-version.outputs.TAG }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Get package.json version
        id: get-version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "TAG=v$VERSION" >> $GITHUB_OUTPUT
          # alternative:
          # VERSION=$(npm pkg get version | tr -d '"')
      - name: Create new release
        id: create-release
        env:
          TAG: ${{ steps.get-version.outputs.TAG }}
          COMMIT_SHA: ${{ github.event.pull_request.merge_commit_sha }}
        uses: actions/github-script@v8
        with:
          script: |
            const script = require('./.github/scripts/create_release.js');
            await script({github, context, core});
  deploy:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.create-release.outputs.tag }}
      - name: Deploy
        run: |
          echo "Deploying version ${{ needs.create-release.outputs.version }}"
          echo "Deployed successfully!"
  sync-back:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: Sync develop branch with main
        env:
          VERSION: ${{ needs.create-release.outputs.version }}
        uses: actions/github-script@v8
        with:
          script: |
            const { default: sync_back } = await import('./.github/scripts/sync_back.js');
            await sync_back({github, context, core});
            # const script = require('./.github/scripts/sync_back.js');
            # await script({github, context, core});
